import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

const courses = [
  { code: 'ELC1037', name: 'Algoritmos e Programação', professor: 'Prof. Dr. Carlos Amaral', attendance: 72, attended: '26/36 aulas', grade: 8.4, next: 'Seg · 08h00', credits: 4, color: 'blue' },
  { code: 'ELC1052', name: 'Cálculo I', professor: 'Profa. Dra. Marina Souza', attendance: 58, attended: '21/36 aulas', grade: 7.2, next: 'Ter · 10h00', credits: 6, color: 'green' },
  { code: 'ELC1044', name: 'Física I', professor: 'Prof. Dr. Roberto Lima', attendance: 64, attended: '23/36 aulas', grade: 6.8, next: 'Qua · 14h00', credits: 4, color: 'purple' },
  { code: 'ELC1061', name: 'Álgebra Linear', professor: 'Profa. Dra. Ana Ferreira', attendance: 80, attended: '29/36 aulas', grade: 9.1, next: 'Sex · 08h00', credits: 4, color: 'yellow' },
]
const navItems = [
  { id: 'dashboard', icon: '⌘', label: 'Dashboard', target: 'dashboard' }, { id: 'subjects', icon: '▣', label: 'Disciplinas', target: 'subjects' },
  { id: 'schedule', icon: '□', label: 'Horários', target: 'schedule' }, { id: 'ru', icon: '♜', label: 'Restaurante Universitário', target: 'ru' },
  { id: 'grades', icon: '⌁', label: 'Notas', target: 'grades' }, { id: 'history', icon: '▤', label: 'Histórico', target: 'grades' },
  { id: 'support', icon: '?', label: 'Suporte', target: 'support' },
]
const schedule = [
  ['08:00', '09:40', 'Algoritmos e Programação', 'Lab 2 — CT', 'Prática', 'blue'], ['10:00', '11:40', 'Cálculo I', 'Sala 103 — CCR', 'Teórica', 'green'],
  ['12:00', '13:30', 'Almoço — RU Central', 'Restaurante Universitário', 'RU', 'red'], ['14:00', '15:40', 'Física I', 'Auditório A — CT', 'Teórica', 'purple', true], ['16:00', '17:40', 'Álgebra Linear', 'Sala 205 — CT', 'Teórica', 'yellow'],
]

function Sidebar({ active, collapsed, onToggle, onNavigate }) {
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}>
    <div className="brand"><div className="brand-mark">◇</div><div className="brand-name"><strong>UFSM</strong><span>PORTAL ACADÊMICO</span></div><button className="collapse-button" onClick={onToggle} aria-label={collapsed ? 'Expandir barra lateral' : 'Recolher barra lateral'}>{collapsed ? '›' : '‹'}</button></div>
    <div className="sidebar-rule" /><p className="nav-label">NAVEGAÇÃO</p>
    <nav>{navItems.map(item => <button aria-current={active === item.id ? 'page' : undefined} className={`nav-link ${active === item.id ? 'active' : ''}`} key={item.id} onClick={() => onNavigate(item)}><span>{item.icon}</span><b>{item.label}</b><i className="nav-tooltip">{item.label}</i></button>)}</nav>
    <div className="semester"><i /><div><b>2025/1 — Ativo</b><span>Semestre em curso</span></div></div>
  </aside>
}
function Header() { const [open, setOpen] = useState(false); return <header className="topbar"><div className="welcome"><h1>Bom dia, Ana Carolina <span>👋</span></h1><p>Segunda-feira, 24 de agosto de 2026</p></div><div className="head-actions"><label className="search"><span>⌕</span><input placeholder="Buscar disciplinas..." /></label><div className="notification-wrap"><button aria-label="Notificações" className="bell" onClick={() => setOpen(!open)}>♧<b /></button>{open && <div className="notifications"><strong>Notificações</strong><p>Você não possui novas notificações.</p></div>}</div><div className="profile"><div><b>Ana Carolina Melo</b><span>Engenharia Elétrica · 4º sem.</span></div><div className="avatar">AC</div></div></div></header> }
function Stat({ symbol, value, title, note, color }) { return <article className="stat-card"><span className={`stat-icon ${color}`}>{symbol}</span><div><strong>{value}</strong><b>{title}</b><small>{note}</small></div></article> }
function Course({ c }) { return <article className={`course-card ${c.color}`}><div className="course-top"><div><code>{c.code}</code><h3>{c.name}</h3></div><em>{c.credits} cr.</em></div><p className="professor">{c.professor}</p><div className="meter-label"><span>Frequência: {c.attended}</span><b>{c.attendance}%</b></div><div className="bar"><i style={{ width: `${c.attendance}%` }} /></div><div className="grade-line"><div className="bar"><i style={{ width: `${c.grade * 10}%` }} /></div><b>{c.grade.toFixed(1)}</b></div><div className="next"><span>Próxima aula</span><b>{c.next}</b></div></article> }
function Schedule() { return <section id="schedule" className="schedule-section"><div className="section-heading"><h2>Hoje — Segunda-feira</h2><button>Grade →</button></div><div className="timeline">{schedule.map(([start, end, name, room, type, color, current]) => <article className={`schedule-item ${color} ${current ? 'current' : ''}`} key={start}><div className="time"><b>{start}</b><span>{end}</span></div><div className="track"><i /></div><div className="schedule-info"><div><h3>{name}</h3>{current && <strong>AGORA</strong>}</div><p>{room}</p><em>{type}</em></div></article>)}</div></section> }
function Grades() { const marks = [[8.5, 8.3], [7.4, 7], [6.2, 7.1], [9, 9.2]]; return <section className="grades" id="grades"><div className="section-heading"><div><h2>Notas e desempenho</h2><p>Acompanhamento parcial do semestre</p></div><button>Ver boletim →</button></div><div className="table-wrap"><table><thead><tr><th>DISCIPLINA</th><th>T1</th><th>T2</th><th>T3</th><th>FINAL</th><th>SITUAÇÃO</th></tr></thead><tbody>{courses.map((c, i) => <tr key={c.code}><td><code>{c.code}</code><span>{c.name}</span></td><td>{marks[i][0]}</td><td>{marks[i][1]}</td><td>—</td><td className={c.grade >= 7 ? 'good' : 'warn'}>{c.grade.toFixed(1)}</td><td><em className={c.grade >= 7 ? 'approved' : 'attention'}>{c.grade >= 7 ? 'Em andamento' : 'Atenção'}</em></td></tr>)}</tbody></table></div></section> }
function RU() { const cells = Array.from({ length: 289 }, (_, i) => <i className={(i * 7 + Math.floor(i / 17) * 3) % 5 < 2 ? 'dark' : ''} key={i} />); return <section className="ru-card" id="ru"><div className="ru-heading"><span>RESTAURANTE UNIVERSITÁRIO</span><b>RU CENTRAL</b></div><p>Saldo disponível</p><div className="balance">R$ 42,00</div><small>7 refeições · R$ 6,00 por refeição</small><div className="ru-content"><div className="qr">{cells}</div><div><b>Ana Carolina Melo</b><span>Matrícula 202112345</span><button>Recarregar saldo</button></div></div><div className="menu"><span>ALMOÇO DE HOJE</span><p>Arroz integral, feijão, frango grelhado e salada fresca.</p></div></section> }
function App() { const [active, setActive] = useState('dashboard'); const [collapsed, setCollapsed] = useState(false); const [message, setMessage] = useState(''); const navigate = item => { setActive(item.id); setMessage(`${item.label} selecionado`); document.getElementById(item.target)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }; return <div className={`app ${collapsed ? 'sidebar-is-collapsed' : ''}`}><Sidebar active={active} collapsed={collapsed} onToggle={() => setCollapsed(value => !value)} onNavigate={navigate} /><main><Header /><div className="page" id="dashboard"><p className="nav-feedback" aria-live="polite">{message}</p><section className="stats"><Stat symbol="▥" value="4" title="Disciplinas Ativas" note="2025/1" color="blue" /><Stat symbol="▥" value="82%" title="Frequência Média" note="Meta: 75%" color="green" /><Stat symbol="▰" value="8.24" title="CR Acumulado" note="Atualizado ontem" color="purple" /><Stat symbol="✓" value="68" title="Créditos Cursados" note="de 180 totais" color="mint" /></section><div className="dashboard-grid"><div className="left-column"><section id="subjects"><div className="section-heading"><h2>Disciplinas em Andamento</h2><button>Ver todas →</button></div><div className="courses">{courses.map(c => <Course c={c} key={c.code} />)}</div></section><Grades /></div><div className="right-column"><Schedule /><RU /></div></div><section id="support" className="support-card"><div><b>Precisa de ajuda?</b><span>Fale com a equipe de suporte acadêmico.</span></div><button>Entrar em contato →</button></section></div></main></div> }
createRoot(document.getElementById('root')).render(<App />)
